# Generated by Django 6.0.7 on 2026-07-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_consommation',
            field=models.CharField(choices=[('sur_place', 'Sur place'), ('a_emporter', 'À emporter'), ('livraison', 'Livraison')], default='sur_place', max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True),
        ),
    ]
