# Generated by Django 6.0.7 on 2026-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('livraison', 'En cours de livraison'), ('terminée', 'terminée')], default='en_attente', max_length=20),
        ),
    ]
