# Generated by Django 6.0.7 on 2026-07-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_produit_est_vedette_produit_prix_promo'),
    ]

    operations = [
    ]
