# Generated by Django 6.0.7 on 2026-07-24 16:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_produit_est_vedette_produit_prix_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
